/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package atividade.revisao;

public class App {

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        String valor = "A";
        switch(valor){
            case "A": System.out.println("A");break;
            case "B": System.out.println("B");break;
            case "C": System.out.println("C");break;
            case "D": System.out.println("D");break;
            case "E": System.out.println("E");break;
            default: System.out.println("Padrão");
        }
    }
}
